// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// PieceExpIntensity1
List PieceExpIntensity1(arma::vec Y, arma::vec Rates, int B, double Poi);
RcppExport SEXP PieceExpIntensity_PieceExpIntensity1(SEXP YSEXP, SEXP RatesSEXP, SEXP BSEXP, SEXP PoiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rates(RatesSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type Poi(PoiSEXP);
    rcpp_result_gen = Rcpp::wrap(PieceExpIntensity1(Y, Rates, B, Poi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"PieceExpIntensity_PieceExpIntensity1", (DL_FUNC) &PieceExpIntensity_PieceExpIntensity1, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PieceExpIntensity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
